version: 2.1
orbs:
  pulumi: pulumi/pulumi@3.39.1
jobs:
  build:
    docker:
      - image: circleci/node:7.10
      - image: localstack/localstack:${LS_VERSION}
    working_directory: ~/repo
    steps:
      - checkout
      - pulumi/login
      - setup_remote_docker
      - run:
          command: |
            make destroy
            make all
            make deploy